# Generated by Django 4.2.3 on 2023-08-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_username_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='get_random_string', max_length=30, unique=True),
        ),
    ]
