# Generated by Django 4.2.3 on 2023-08-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('confId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('confName', models.CharField(max_length=255)),
                ('detailConf', models.CharField(max_length=255)),
                ('confImages', models.CharField(max_length=255)),
            ],
        ),
    ]
