# Generated by Django 4.2.3 on 2023-09-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='confImages',
            field=models.ImageField(blank=True, null=True, upload_to='conference_images/'),
        ),
    ]
