# Generated by Django 4.2.3 on 2023-08-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('jurnalId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('jurnalName', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('detailJurnal', models.CharField(max_length=255)),
                ('jurnalImages', models.CharField(max_length=255)),
            ],
        ),
    ]
