# Generated by Django 4.2.3 on 2023-08-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('repoId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('repoName', models.CharField(max_length=255)),
                ('address', models.CharField(choices=[('kota', 'kota'), ('provinsi ', 'provinsi '), ('negara ', 'negara ')], max_length=255)),
                ('detailRepo', models.CharField(max_length=255)),
                ('repoImages', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
