# Generated by Django 4.2.3 on 2023-08-31 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_remove_repository_repoimages_repository_background_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='RepoImages',
            new_name='repoImages',
        ),
    ]
