# Generated by Django 4.2.3 on 2023-09-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0004_repository_urlsrepo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='urlsRepo',
            field=models.URLField(blank=True, error_messages={'invalid': 'Masukkan URL yang valid.'}, null=True),
        ),
    ]
