# Generated by Django 4.2.3 on 2023-09-05 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0005_alter_repository_urlsrepo'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
